### ISSUE TITLE
Don't Assume Previous Webpack Knowledge

### ISSUE THREAD

**Issue by Snugug** [vuejs/vue-ssr-docs#10]
There are likely going to be many uses who are not already familiar with webpack as there are a number of other bundling options and users are likely to choose one and run with it. Given that this documentation is _reliant_ on webpack, it should include the basic documentation for configuring webpack that [it assumes users already have](http://ssr.vuejs.org/en/build-config.html)

**Comment by yyx990803** [comment]
webpack itself now has [great docs](https://webpack.js.org/), I don't see a point of duplicating it in this guide where we explicit say it relies on webpack.

**Comment by matthew-dean** [comment]
Vue w/ SSR isn't reliant on Webpack. In fact, I have it working (mostly, still setting up) just fine with Rollup.
