### ISSUE TITLE
设置 runInNewContext 出现内存泄漏

### ISSUE THREAD

**Issue by baijikang** [vuejs/vue-ssr-docs#109]
系统： mac
node 版本：6.10.3
vue 版本 ：2.4.1
项目：vue-hackernews-2.0（官方 demo）

经过几千次请求测试发现，设置 runInNewContext = false 或者 'once' 会出现内存泄漏（200MB 左右）。不设置的 runInNewContext 内存就会控制的比较好（60MB）左右。

请问是 node 版本问题吗 ？

**Comment by baijikang** [comment]
我用 pm2 启动的项目，和这个有关系吗 ？

**Comment by yyx990803** [comment]
官方 demo 如果不改懂，绝对没有内存泄漏，应该是用法问题，或者可能跟 pm2 有关，但那样的话不应该在这里开 issue。
