### ISSUE TITLE
Vuex getters doesn't get pre-rendered

### ISSUE THREAD

**Issue by lindesvard** [vuejs/vue-ssr-docs#111]
Hi,

I try to get SSR working with Vuex Getters without any luck. I don't get any markup pre-rendered when I have a computed property with getters

```js
export default {
  computed: {
    articles() {
      // return this.$store.getters.articles; // this works but all my articles are rendered at client
      return this.$store.state.articles[this.$store.state.tag]; // this works and gets pre-rendered
    }
  },
  asyncData ({ store }) {
    return store.dispatch('FETCH_ARTICLES');
  },
}
```

My getters.js looks like this:
```js
export default {
  articles (state) {
    const { articles, tag } = state

    return articles[tag];
  },
}
```

Am I missing something or is this expected behaviour?

**Comment by chrisvfritz** [comment]
Hi @lindesvard - the official Vue [forum](https://forum.vuejs.org) or [chat](https://chat.vuejs.org) are actually the best places for support questions.
