### ISSUE TITLE
Data pre fetch: When resolving which components not to render, we need to consider the same component in different routes

### ISSUE THREAD

**Issue by cjblomqvist** [vuejs/vue-ssr-docs#124]
Scenario: Two routes; A, B. Both point to component C, which loads data based upon the name of the route. When filtering components, this means a transition from A to B will not get its component loaded.

I'm a little low on time, so don't have time for proper PR and more detailed explanation, but below is a snippet from my code we use:

```javascript
// we only care about none-previously-rendered components,
// so we compare them until the two matched lists differ
// Also, if same components but different routes - we
// can't be sure we don't need to reload the data, so
// reload data in such cases (make everything differ)
let diffed = to.name !== from.name;
const activated = matched.filter((c, i) => {
    return diffed || (diffed = (prevMatched[i] !== c));
})
```

**Comment by LinusBorg** [comment]
This is over 1 months old and frankly, from the short description I'm not sure where this relates to SSR, so I'll close it.
