### ISSUE TITLE
vue ssr express boilerplate

### ISSUE THREAD

**Issue by besnikh** [vuejs/vue-ssr-docs#15]
Hi,
I am building my app using Vue 2, and I love it, but I see that I will need SSR on most of my pages but just by following documentation I think I am unable to finish it. 

Is there any boilerplate of Vue SSR + Express + Vuex(maybe) where I could see how the structure is, how things connect and interact with each other... I would just need a hint. 

Looking forward to receive from someone,
Regards,
Cheers!

**Comment by Devil-Cong** [comment]
@besnikh  
Maybe you should try the [Nuxt](https://nuxtjs.org/).

**Comment by egoist** [comment]
https://github.com/vuejs/vue-hackernews-2.0 is a nice ssr example

There's also a plan for official ssr template.

**Comment by besnikh** [comment]
@Devil-Cong  I am considering using Nuxt, their documentation looks clean but their demo does not seem so fast at rending like the Vue-hackernews demo for example. 

@egoist I have to take a deeper look at demo, the thing which I can't get my head around is using server entry, client entry.. I don't get it. 

Let's say I build my app, I understand I would need node to run on 'client', but do I need anything else running on client side, can I make the client side communicate with my backend which will be express + nodejs. 
I hope you understand my question, and I would really appreciate if someone would be ready to answer me just couple of questions regarding this "issue" I am having.

**Comment by sethdorris** [comment]
@besnikh why would you need node to run on client? 

I am having issues with the documentation, understanding how the factory pattern for the createApp works if node does not support ES6 modules yet? My app continues to break on the server side of things due to this, and then when I try converting that to commonJS module system, it also breaks when I try to var createRouter = require('vue-router').createRouter;

**Comment by wangyi7099** [comment]
[boilerplate](https://github.com/YvesCoding/vue-ssr-boilerplate) Inspired by vue-hackernews2.0
