### ISSUE TITLE
关于文档有些疑问

### ISSUE THREAD

**Issue by Zegapaiz** [vuejs/vue-ssr-docs#186]
built-server-bundle.js  文件怎么来的？
vue-ssr-server-bundle.json 文件又是怎么来的
baseConfig 里面的配置是怎样的 有示例看一下吗？
没看明白在这里webpack是怎么用的，是当做一个函数引用的还是要手动webpack把vue 文件打包一下？
文档衔接看的好突然= =

**Comment by dear-lizhihua** [comment]
https://ssr.vuejs.org/zh/guide/build-config.html
```
  // 这是将服务器的整个输出
  // 构建为单个 JSON 文件的插件。
  // 默认文件名为 `vue-ssr-server-bundle.json`
  plugins: [
    new VueSSRServerPlugin()
  ]
```
示例参考官方 hacknews 和 Vue SSR Demo：
- https://github.com/vuejs/vue-hackernews-2.0
- https://github.com/youngwind/blog/issues/112
