### ISSUE TITLE
Is there any document about how to bundle components and make them support SSR?

### ISSUE THREAD

**Issue by njleonzhang** [vuejs/vue-ssr-docs#192]
I have several reusable components which have been bundled by webpack to `umd` and published to `npm`. Now they can not support SSR, is there any document for me?

**Comment by LinusBorg** [comment]
There's two simple rules:

1. Don't use any browser APIs, e.g. `window` or `document` without checking if they exist - they don't exist on the server, obviously
2. Code in `mounted` and the following lifeccle hooks is not run, only `beforeCreate` and `created`.

Docs about these limitations are here: https://ssr.vuejs.org/guide/universal.html#access-to-platform-specific-apis

These all appl to complonents as well and there's nothing else I could tell you.
