### ISSUE TITLE
Missing information about hydration with $mount

### ISSUE THREAD

**Issue by Askoth** [vuejs/vue-ssr-docs#193]
@chrisvfritz 

Following up our chat last week, it was hard to find out that hydration was also possible using [vm.$mount](https://vuejs.org/v2/api/#vm-mount).

Only data-server-rendered case is mentioned here https://ssr.vuejs.org/guide/hydration.html

$mount is used only as part of the explanation why it doesn’t fit but the 2nd argument (bool for hydration) is omitted. 

Thanks again for the chat, I’ve been enjoying the vue.

**Comment by chrisvfritz** [comment]
Glad to hear you're enjoying the Vue. 😄 And thanks for helping us improve the doc! What do you think about [this addition](https://github.com/vuejs/vue-ssr-docs/pull/194)?
