### ISSUE TITLE
Client data fetching in beforeMount mixin double-fetches

### ISSUE THREAD

**Issue by phil294** [vuejs/vue-ssr-docs#210]
Option 2, [Fetch data after the matched view is rendered](https://ssr.vuejs.org/guide/data.html#client-data-fetching), calls `asyncData` in `beforeMount`.

The pseudo-syntax is
```js
if (asyncData)
  asyncData()
```

This does not check if `asyncData` was already called by the server! Thus, guided by the official docs, this leads to duplicate fetches. In the case of dynamic module registration, even to duplicate modules.

What is the suggested way around this? Could we please have some documentation here?

If this issue is unclear, I explain it in greater detail at https://github.com/vuejs/vue/issues/9252, including a repro link. But it is more of a docs issue

**Comment by LinusBorg** [comment]
Reopened afer I realized this does belong here after all (related: https://github.com/vuejs/vue-ssr-docs/issues/210)

**Comment by phil294** [comment]
This was fixed nicely with https://github.com/vuejs/vue-ssr-docs/pull/214 with the addition of `serverPrefetch()` and updated docs. Great.

Store code splitting with `preserveState: true` does not work for me (state is missing; shouldnt it be `preserveState: false` server-side anyway? nothing to preserve here, hence empty state), however that is a seperate issue, not to be handled here.
