### ISSUE TITLE
Add info about MiniCssExtractPlugin

### ISSUE THREAD

**Issue by denisinvader** [vuejs/vue-ssr-docs#212]
I've spent half of my workday trying to render my app on a server and didn't understand what's wrong. The problem was in MiniCssExtractPlugin because it doesn't care about SSR. 

I had `document is not defined` error at first. I've tried to mock document in NodeJs using JSDOM (I understood that something wrong if I need to do it) and the error has gone, but nothing just rendered, `router.onReady` didn't resolve anything.

Many hours of searching later I've accidentally found some issue (can't provide a reference) where someone said that MiniCssExtractPlugin doesn't care about SSR. Then I've switched to ExtartTextPlugin and everything worked.

So please add a note about this plugin in docs.

**Comment by LinusBorg** [comment]
Closing in favor of #187
