### ISSUE TITLE
Cookies and LocalStorage: provide a basic example

### ISSUE THREAD

**Issue by niksubramanian** [vuejs/vue-ssr-docs#22]
Hi there,

First of all, wonderful work on the docs - I went through them and found them to be a pleasure to use and implement.

A point of improvement would be to give an example on: 
* how to handle setting and getting localStorage.
* how to handle setting and getting a cookie.

I'd argue this would be useful for a number of reasons:
* There seems to be a general lack of documentation about this issue, resulting in a number of unanswered questions in the forum, such as these: [example 1](https://forum.vuejs.org/t/how-to-store-jwt-token-in-vue-2-0-ssr/5342), [example 2](https://forum.vuejs.org/t/authentication-in-ssr/4972)
* Most sites that require the complexity of SSR probably also require handling login/authentication management.

Thanks in advance, and keep up with the great work!

**Comment by niksubramanian** [comment]
Perhaps to get the ball rolling on this issue: I'd love to contribute, but I'd need at least some pointer on how to solve these issues at a more general level. If anyone can point me in the right direction, I wouldn't mind writing the docs required to solve this issue.

**Comment by Lokesh235** [comment]
Hi, 
I am a beginner here. Is there any docs available for SSR authentication problem pointed out by @niksubramanian ?

Trying to create a project with SSR veu and django as backend. In this set up need to use token provided by backend in each request. If I store token in state it is visible in html source and if I set httponly and secure_flag to True then I can't read cookie. 

Hope to get some ideas to solve this issue. Thanks.

**Comment by abhineet97** [comment]
@niksubramanian, why did you close this issue? Did you find these docs elsewhere? If yes, then can you please share them with us?
