### ISSUE TITLE
官网文档，中文与 英文请不要区别对待。

### ISSUE THREAD

**Issue by yuncode** [vuejs/vue-ssr-docs#286]
中文： [带有逻辑配置的组件-logic-collocation-with-components](https://ssr.vuejs.org/zh/guide/data.html#%E5%B8%A6%E6%9C%89%E9%80%BB%E8%BE%91%E9%85%8D%E7%BD%AE%E7%9A%84%E7%BB%84%E4%BB%B6-logic-collocation-with-components)

英文： [logic-collocation-with-components](https://ssr.vuejs.org/guide/data.html#logic-collocation-with-components)

示例代码 中文少了一大截。

**Comment by yyx990803** [comment]
这不是区别对待，只是更新或是 merge PR 不一定会同步。中文翻译由社区贡献和维护，你有兴趣可以 PR，但你没资格提要求。

**Comment by yuncode** [comment]
> 这不是区别对待，只是更新或是 merge PR 不一定会同步。中文翻译由社区贡献和维护，你有兴趣可以 PR，但你没资格提要求。
开源就是给我提要求的资格。

**Comment by yuncode** [comment]
你官网顶部给个提醒，大家就不会有误解。如果中文常年没人贡献，是几年前的，好吗？
看了旧文档一头雾水。

**Comment by Justineo** [comment]
如果想得到帮助，就得好好说话。发泄怨气，你说会得到什么？

**Comment by sodatea** [comment]
既然这么有空的话，麻烦帮我们审一下这个 PR 吧，看看有没有翻译或格式问题
https://github.com/vuejs/vue-ssr-docs/pull/230

文档翻译没有更新无非两个原因：
1. 没人翻译
2. 有人翻译，但没人审核，所以无法合并

自己动手解决一下问题呗。

**Comment by yyx990803** [comment]
不想和你这种人废话，block 了。
