### ISSUE TITLE
Translation project for japan and korean

### ISSUE THREAD

**Issue by kazupon** [vuejs/vue-ssr-docs#3]
We started the `ja` (lead by @kazupon) and `ko` (lead by @ChangJoo-Park) translation project with [GitLocalize](https://gitlocalize.com).

GitLocalize repository: https://gitlocalize.com/repo/62
GitHub Repository: https://github.com/open-source-translators/vue-ssr-docs

If you are interested in it, please tell us. 😉

**Comment by shadeofgod** [comment]
@kazupon  hey could you pls make a Chinese branch on this GitLocalize repo so I can join?  I'm currently working on it and found out there is another pull request about Chinese translation, guess we could work together on it.

**Comment by kazupon** [comment]
@shadeofgod 
Thank you for having an interest in GitLocalize.
We can create a `Chinese` language translation on GitLocalize, and we can invite you.

Currently, in about #2, Translation is progressing, but I think you need to coordinate with @dear-lizhihua. 😉

**Comment by sotayamashita** [comment]
Hi @shadeofgod, I am an engineer of @gitlocalize and If you have any question, please feel free to ask me with this issue or email address which is on my GitHub profile. Thanks

**Comment by shadeofgod** [comment]
yeah I've talked that with dear-lizhihua and he agreed.
that would be much appreciated if you can create a chinese translation
on this project and invite both of us since using pull request is so
inconvenient for multiple people to cooperate on this translation
project.

regards

**Comment by sotayamashita** [comment]
@shadeofgod I have created Chinese team on GitLocalize but you need sigh up on GitLocalize first. Please let me know when you created your account on GitLocalize. I will assign you and invite our translation organisation.

https://gitlocalize.com/

**Comment by shadeofgod** [comment]
I signed in with github account weeks ago, not sure if that works.

https://gitlocalize.com/users/shadeofgod

**Comment by sotayamashita** [comment]
@shadeofgod I invite you https://gitlocalize.com/repo/62. Please check this out

**Comment by shadeofgod** [comment]
yeah got that

arigato!

**Comment by shadeofgod** [comment]
hey some of the original files on Gitlocalize seems glitched
you can check this one:
https://gitlocalize.com/repo/62/zh/en/hydration.md

**Comment by sotayamashita** [comment]
@shadeofgod Oh, we are sorry about that and we are investigating now. If we solve this problem, we will let you know.  Thank you for your report. :bow:

**Comment by ChangJoo-Park** [comment]
@kazupon I finished translation in Korean. However I need to check some files in `.md` . Please merge Korean docs.

**Comment by kazupon** [comment]
You can push PR to this repo via GitLocalize review request. :)

<img width="1198" alt="pr-via-gitlocalize" src="https://user-images.githubusercontent.com/72989/26937693-0ac6e5d4-4cad-11e7-9ccc-0a19c0841291.png">

**Comment by ChangJoo-Park** [comment]
Thanks!! 
I found Gitlocalize updated about code translate. I'll translate all about code blocks.

**Comment by sotayamashita** [comment]
@ChangJoo-Park You welcome. It is @chikathreesix's effort

**Comment by chikathreesix** [comment]
@ChangJoo-Park Oh sorry, I found the bug on the code block translation so rolled it back for now. Will make it ready by today or tomorrow. 🙇

**Comment by ChangJoo-Park** [comment]
@chikathreesix 
yesterday, I was surprised that editing code blocks feature was removed. but I am OK. If I get some idea, I am going to send a message in gitter chat room. GitLocalize is awesome! 🎉

**Comment by dear-lizhihua** [comment]
@chikathreesix 
Thanks gitlocalize team effort and look forward to improvement

**Comment by chikathreesix** [comment]
@ChangJoo-Park @dear-lizhihua Sorry to keep you guys waited, we have just launched the feature to edit code blocks and also fixed few bugs around HTML tags! Try it out and give us any feedbacks :)
