### ISSUE TITLE
Vue SSR guide Chinese document data prefetching and status module has an extra closing parenthesis

### ISSUE THREAD

**Issue by summertzz** [vuejs/vue-ssr-docs#314]
### Steps to reproduce
1. open (https://ssr.vuejs.org/zh/guide/data.html)
![image](https://user-images.githubusercontent.com/27355995/109610377-a11fdd00-7b67-11eb-8810-76f0c230034a.png)

**Comment by lsbbd** [comment]
https://ssr.vuejs.org/zh/guide/streaming.html#%E6%B5%81%E5%BC%8F%E4%BC%A0%E8%BE%93%E8%AF%B4%E6%98%8E-streaming-caveats

![image](https://user-images.githubusercontent.com/18237955/109652212-71d69380-7b9a-11eb-8324-af2d089f47bc.png)

https://ssr.vuejs.org/zh/guide/universal.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8C%87%E4%BB%A4

![image](https://user-images.githubusercontent.com/18237955/109652323-96cb0680-7b9a-11eb-8125-b58e369f5f6c.png)
