### ISSUE TITLE
Include an example of how to handle "runInNewContext: false" with store modules

### ISSUE THREAD

**Issue by jazoom** [vuejs/vue-ssr-docs#36]
It is not immediately apparent that each store module needs to be a function that returns a fresh module, which needs to be combined with other store modules when the root store is created afresh.

The above sentence is really confusing. See discussion here to understand what I mean:

https://forum.vuejs.org/t/debugging-state-pollution-with-the-new-behaviour-of-vue-2-3-ssr/11724

**Comment by LinusBorg** [comment]
https://ssr.vuejs.org/guide/data.html#store-code-splitting
