### ISSUE TITLE
How could I disable prefetch injection?

### ISSUE THREAD

**Issue by lsycxyj** [vuejs/vue-ssr-docs#74]
I want to keep preload tags and don't want to prefetch async chunks, but I can only find the `shouldPreload ` options to disable preload. How could I achieve that? Thank you very much.

**Comment by yyx990803** [comment]
prefetch is low-priority and the browser decides whether to fetch it depending on network conditions and resource priorities. Why would you want to disable it?

**Comment by lsycxyj** [comment]
For example, I have many different async chunks of different pages and they are not needed in this page. Although prefetch is low-priority, I notice that they are fetched concurrently with other resources, which means it will occupy the bandwidth and slow the download of critical resources (especially in slow network).

**Comment by yyx990803** [comment]
The difference between `prefetch` vs. `preload` is that it will not slow down other critical resources. By design it will only fetch resources when the browser is considered idle.

**Comment by lsycxyj** [comment]
In fact, it does slow down other resources.
Notice the time of vendor chunk. Chunk 3-6 are chunks of other pages.

![](https://github.com/lsycxyj/markdownPhotos/raw/master/demo-slow-prefetch.png)
![](https://github.com/lsycxyj/markdownPhotos/raw/master/demo-slow-prefetch-2.png)

**Comment by yyx990803** [comment]
You sure it actually affects the vendor chunk? The vendor chunk takes longer simply because it's the biggest chunk.

**Comment by lsycxyj** [comment]
In my case it does affect. As you can see, I made two cases. The first one is with a 90kb of chunk 6, and it took 50+s to load the vendor chunk. The second one is with a 6kb of chunk 6, and it took only 40+s.

**Comment by lsycxyj** [comment]
Both of the vendor chunks are of the same size

**Comment by ilyaskorik** [comment]
And how to do this? I do not want to load 50+ localizations when I need one

**Comment by Daner1990** [comment]
when you call createBundleRenderer, you only need to return false when call shouldPrefetch

`function createRenderer(bundle, options) {
    // https://github.com/vuejs/vue/blob/dev/packages/vue-server-renderer/README.md#why-use-bundlerenderer
    return createBundleRenderer(bundle, Object.assign(options, {
        template,
        // for component caching
        cache: LRU({
            max: 1000,
            maxAge: 1000 * 60 * 15
        }),
        // this is only needed when vue-server-renderer is npm-linked
        basedir: resolve('../dist'),
        inject: false,
        renderStyles:()=>{

        },
        renderState:()=>{

        },
        renderScripts:()=>{

        },
        shouldPreload: (file, type) => {
            // https://fetch.spec.whatwg.org/#concept-request-destination
            console.log(file,type);
            if (type === 'script' || type === 'style') {
                return true
            }

            if (type === 'font') {
                return /\.woff2$/.test(file)
            }
            if (type === 'image') {}
        },
        shouldPrefetch: (file, type) => {
            return false;
        },
        // recommended for performance
        runInNewContext: false
    }))
}
`
