### ISSUE TITLE
data-server-rendered="true"

### ISSUE THREAD

**Issue by bjunc** [vuejs/vue-ssr-docs#75]
The docs say hydration takes place when the app's root element has `data-server-rendered="true"`.  However, it seems that the actual attribute Vue looks for is `server-rendered="true"` (no `data-` prefix).

**Comment by 947133297** [comment]
after client side hydration，if the root element do not has` data-server-rendered="true"` ，should i consider it hydration failure ？

**Comment by MaxMilton** [comment]
I was a bit confused about this recently when debugging a custom prerendering setup.

If you have a look [in the source](https://github.com/vuejs/vue/blob/d982e344b39391fe91b6dd91d51b2f0310a45e77/dist/vue.js#L323) it becomes clear that `data-server-rendered="true"` will work. Using `server-rendered="true"` will not trigger client side hydration.

**Comment by yyx990803** [comment]
Closing because it should be `data-server-rendered`. The original issue was probably using an older version.
