### ISSUE TITLE
Get to working code faster

### ISSUE THREAD

**Issue by Snugug** [vuejs/vue-ssr-docs#9]
There are a lot of concepts introduced in this manual, but for most of it actually getting it to run is waved aside until Bundle Rendering. If something doesn't work when we get to that stage, it's hard to work backwards to figure what exactly was the cause of the break. Introducing bundling earlier to get the server running and then continuing on with the other concepts will allow a user's knowledge to grow _with working code_.

**Comment by yyx990803** [comment]
This is intended. We will introduce a CLI template with pre-configured build setup to accompany the guide.
